/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asignacionfichas;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.text.*;
import java.util.Date;
import java.util.TimerTask;
import javax.swing.JOptionPane;

import java.util.LinkedList;
import java.util.Queue;

/**
 *
 * @author jeanh
 */
public class ModeloPrincipal extends javax.swing.JFrame {
    
      ColaPrincipal cola = new ColaPrincipal();

    /**
     * Creates new form ModeloPrincipal
     */
    public ModeloPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCj1 = new javax.swing.JLabel();
        lblCj2 = new javax.swing.JLabel();
        lblCj3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        btnFicha = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnIniciar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSiguiente1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnFinalizar1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnIniciar2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnSiguiente2 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnFinalizar2 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jToolBar3 = new javax.swing.JToolBar();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnIniciar3 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnSiguiente3 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnFinalizar3 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        lblFicha = new javax.swing.JLabel();
        Cajero1 = new javax.swing.JLabel();
        Cajero2 = new javax.swing.JLabel();
        Cajero3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCj1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCj1.setText("0");

        lblCj2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCj2.setText("0");

        lblCj3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCj3.setText("0");

        jTextField4.setText("Atendiendo Ficha #:");

        jTextField5.setText("Atendiendo Ficha #:");

        jTextField6.setText("Atendiendo Ficha #:");

        btnFicha.setText("GENERAR FICHA");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblHora.setText("HORA");

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Titulo.setText("          ÁREA DE CAJAS");

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator5);

        btnIniciar1.setText("Iniciar");
        btnIniciar1.setFocusable(false);
        btnIniciar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIniciar1);
        jToolBar1.add(jSeparator1);

        btnSiguiente1.setText("Siguiente");
        btnSiguiente1.setFocusable(false);
        btnSiguiente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSiguiente1);
        jToolBar1.add(jSeparator2);

        btnFinalizar1.setText("Finalizar");
        btnFinalizar1.setFocusable(false);
        btnFinalizar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinalizar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFinalizar1);
        jToolBar1.add(jSeparator4);

        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator6);

        btnIniciar2.setText("Iniciar");
        btnIniciar2.setFocusable(false);
        btnIniciar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnIniciar2);
        jToolBar2.add(jSeparator7);

        btnSiguiente2.setText("Siguiente");
        btnSiguiente2.setFocusable(false);
        btnSiguiente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSiguiente2);
        jToolBar2.add(jSeparator8);

        btnFinalizar2.setText("Finalizar");
        btnFinalizar2.setFocusable(false);
        btnFinalizar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinalizar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinalizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar2ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnFinalizar2);
        jToolBar2.add(jSeparator9);

        jToolBar3.setRollover(true);
        jToolBar3.add(jSeparator10);

        btnIniciar3.setText("Iniciar");
        btnIniciar3.setFocusable(false);
        btnIniciar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIniciar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar3ActionPerformed(evt);
            }
        });
        jToolBar3.add(btnIniciar3);
        jToolBar3.add(jSeparator11);

        btnSiguiente3.setText("Siguiente");
        btnSiguiente3.setFocusable(false);
        btnSiguiente3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente3ActionPerformed(evt);
            }
        });
        jToolBar3.add(btnSiguiente3);
        jToolBar3.add(jSeparator12);

        btnFinalizar3.setText("Finalizar");
        btnFinalizar3.setFocusable(false);
        btnFinalizar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinalizar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinalizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar3ActionPerformed(evt);
            }
        });
        jToolBar3.add(btnFinalizar3);
        jToolBar3.add(jSeparator13);

        lblFicha.setText("jLabel1");

        Cajero1.setText("Cajero #1");

        Cajero2.setText("Cajero #2");

        Cajero3.setText("Cajero #3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cajero3)
                            .addComponent(Cajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lblCj3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lblCj1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(lblCj2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFicha)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cajero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Cajero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCj2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cajero3))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCj3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Timer te = new Timer(1000, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                 lblHora.setText(sdf.format(new java.util.Date()));
//                 JOptionPane.showMessageDialog(null, "Ha agotado el tiempo de atencion");
             }
         });
    
    Timer t = new Timer(20000, new ActionListener() {
        //10 minuto = 600 000 milisegundos;
       // 1 min=60000
        // 30 segundos=30000
             @Override
             public void actionPerformed(ActionEvent e) {
                 SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                 lblHora.setText(sdf.format(new java.util.Date()));
            JOptionPane.showMessageDialog(null, "El tiempo de atención ha terminado");
             }
             
         });
     private int ficha=0;
    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
      ficha++;
        lblFicha.setText(Integer.toString(ficha));
        cola.Agrega(ficha);
        cola.Muestra();
        if(conta3>1){
            JOptionPane.showMessageDialog(null, "Espere");
        }
        prueba();
    }//GEN-LAST:event_btnFichaActionPerformed

     int conta1=0,conta2=0, conta3=0;
    
    public void prueba(){ 
        if(cola.Mostra1_Vacia()){
            conta1++;
                 int y1 = cola.Extrae();
                 String a1 = String.valueOf(y1);
                 lblCj1.setText(a1);
                 cola.Mostra1_Agrega(y1);
               
        }else{
            if(cola.Mostra2_Vacia()){
                conta2++;
                int y2 = cola.Extrae();
                String a2 = String.valueOf(y2);
                lblCj2.setText(a2);
                cola.Mostra2_Agrega(y2);
              
            }else{
               
                if(cola.Mostra3_Vacia()){
                    conta3++;
                    int y3= cola.Extrae();
                    String a3 = String.valueOf(y3);
                    lblCj3.setText(a3);
                   
                    cola.Mostra3_Agrega(y3);
                }                   
            }
        }
    }
    
      public ModeloPrincipal(JLabel Cajero1, JLabel Cajero2, JLabel Cajero3, JLabel Titulo, JButton btnFinalizar, JButton btnIniciar, JButton btnFicha, JButton btnSiguiente, JToolBar jToolBar1, JLabel lblCj1, JLabel lblCj2, JLabel lblCj3, JLabel lblCola, JLabel lblHora) throws HeadlessException {
        this.Cajero1 = Cajero1;
        this.Cajero2 = Cajero2;
        this.Cajero3 = Cajero3;
        this.Titulo = Titulo;
        this.btnFinalizar1 = btnFinalizar;
        this.btnIniciar1 = btnIniciar;
        this.btnFicha = btnFicha;
        this.btnSiguiente1 = btnSiguiente;
        this.lblCj1 = lblCj1;
        this.lblCj2 = lblCj2;
        this.lblCj3 = lblCj3;
        this.lblHora = lblHora;
    }
    
    
    
    
    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        te.start();
        t.start();
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        int y = cola.Extrae();
            String a2 = String.valueOf(y);
            lblCj1.setText(a2);
            cola.verifica();
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void btnIniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar2ActionPerformed
        te.start();
        t.start();        
// TODO add your handling code here:
    }//GEN-LAST:event_btnIniciar2ActionPerformed

    private void btnIniciar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar3ActionPerformed
        te.start();
        t.start();
    }//GEN-LAST:event_btnIniciar3ActionPerformed

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
         int y = cola.Extrae();
            String a2 = String.valueOf(y);
            lblCj2.setText(a2);
            cola.verifica();
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    private void btnSiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente3ActionPerformed
       int y = cola.Extrae();
            String a2 = String.valueOf(y);
            lblCj3.setText(a2);
            cola.verifica();
    }//GEN-LAST:event_btnSiguiente3ActionPerformed

    private void btnFinalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar1ActionPerformed
         t.stop();
             JOptionPane.showMessageDialog(null, "Transaccion Exitosa.");
            t.restart();
            cola.Mostra1();
            prueba();
    }//GEN-LAST:event_btnFinalizar1ActionPerformed

    private void btnFinalizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar2ActionPerformed
        t.stop();
            JOptionPane.showMessageDialog(null, "Transacción Exitosa.");
            t.restart();
            cola.Mostra2();
            prueba();
    }//GEN-LAST:event_btnFinalizar2ActionPerformed

    private void btnFinalizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar3ActionPerformed
         t.stop();
             JOptionPane.showMessageDialog(null, "Transacción Exitosa.");
            t.restart();
            cola.Mostra3();
            prueba();
    }//GEN-LAST:event_btnFinalizar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cajero1;
    private javax.swing.JLabel Cajero2;
    private javax.swing.JLabel Cajero3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnFinalizar2;
    private javax.swing.JButton btnFinalizar3;
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnIniciar2;
    private javax.swing.JButton btnIniciar3;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton btnSiguiente3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lblCj1;
    private javax.swing.JLabel lblCj2;
    private javax.swing.JLabel lblCj3;
    private javax.swing.JLabel lblFicha;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables
}
